title: Austin Bell
author: Austin Bell
email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
  Hello welcome to my personal website. On this blog you can find
  my portfolio, facts about me, and opinionated wrtiting about code!

# social links
twitter_username: your-twitter-handle
github_username:  your-github-handle

show_excerpts: true # set to false to remove excerpts on the homepage

theme: minima
